### PR TITLE
Update NYSE calendar

### PR DESCRIPTION
**Pull request by glossner**
NYSE calendar valid from 1885 to present. Includes all full day closes, early closes, and late opens.

A test is provided for every year year including time matches for early closes and late opens.

Thanks for your advice while I was modifying these files. I'm fine to change some formatting or any other recommendations you have.

### CODE REVIEW

**Comment by rsheftel** [comment]
Looks like it is causing the CME tests to fail, will need to look into that.

**Comment by glossner** [comment]
The failing cme_bond test imports NYSEExchangeCalendar but as far as I can tell it doesn't use it.

Even so, the test passes in my directory. 

I also checked and it appears I reverted holidays_us.py correctly when we agreed to create holidays_nyse.py.

The diff for market_calendar.py shows I only added the function late_opens(). 

I'll look some more as it seems odd.

**Comment by glossner** [comment]
I pulled the first failing test out and ran it standalone.

cme.schedule('2020-01-01', '2020-01-31', tz='America/Chicago')
                          market_open              market_close
2020-01-02 2020-01-01 17:00:00-06:00 2020-01-02 16:00:00-06:00
2020-01-03 2020-01-02 17:00:00-06:00 2020-01-03 16:00:00-06:00
2020-01-06 2020-01-05 17:00:00-06:00 2020-01-06 16:00:00-06:00
2020-01-07 2020-01-06 17:00:00-06:00 2020-01-07 16:00:00-06:00
2020-01-08 2020-01-07 17:00:00-06:00 2020-01-08 16:00:00-06:00
2020-01-09 2020-01-08 17:00:00-06:00 2020-01-09 16:00:00-06:00
2020-01-10 2020-01-09 17:00:00-06:00 2020-01-10 16:00:00-06:00
**2020-01-13 2020-01-12 17:00:00-06:00 2020-01-13 16:00:00-06:00**
2020-01-14 2020-01-13 17:00:00-06:00 2020-01-14 16:00:00-06:00
2020-01-15 2020-01-14 17:00:00-06:00 2020-01-15 16:00:00-06:00
2020-01-16 2020-01-15 17:00:00-06:00 2020-01-16 16:00:00-06:00
2020-01-17 2020-01-16 17:00:00-06:00 2020-01-17 16:00:00-06:00
2020-01-20 2020-01-19 17:00:00-06:00 2020-01-20 12:00:00-06:00
2020-01-21 2020-01-20 17:00:00-06:00 2020-01-21 16:00:00-06:00
2020-01-22 2020-01-21 17:00:00-06:00 2020-01-22 16:00:00-06:00
2020-01-23 2020-01-22 17:00:00-06:00 2020-01-23 16:00:00-06:00
2020-01-24 2020-01-23 17:00:00-06:00 2020-01-24 16:00:00-06:00
2020-01-27 2020-01-26 17:00:00-06:00 2020-01-27 16:00:00-06:00
2020-01-28 2020-01-27 17:00:00-06:00 2020-01-28 16:00:00-06:00
2020-01-29 2020-01-28 17:00:00-06:00 2020-01-29 16:00:00-06:00
2020-01-30 2020-01-29 17:00:00-06:00 2020-01-30 16:00:00-06:00
2020-01-31 2020-01-30 17:00:00-06:00 2020-01-31 16:00:00-06:00

assert pd.Timestamp('2020-01-12 17:00:00', tz='America/Chicago') == schedule.at['2020-01-13', 'market_open']

schedule.at['2020-01-13', 'market_open']   2020-01-12 17:00:00-06:00

The value is in the data.

One thing that might be helpful is in the master branch to run the test with 
from .exchange_calendar_nyse import NYSEExchangeCalendar
comment out in exchange_calendar_cme.py

If there is some kind of rule name conflict I guess it would have to be there. In my fork it didn't make any difference. Both passed.

All of the CME exchange calendars inherit from MarketCalendar - not NYSEExchangeCalendar. I can't see how adding a new function late_opens() could break them but we could revert it back.

Just curiously, if you rerun the tests on the main branch do they still all pass?

Thanks.

**Comment by glossner** [comment]
The original development work was done under windows. I created a new Ubuntu 18.04 VM with only Anaconda python 3.8 installed. I cloned my repository, installed it, ran the tests. They all passed.

**Comment by rsheftel** [comment]
@glossner OK, I will take a look and see how to get everything on Travis to pass

**Comment by rsheftel** [comment]
The errors related to pandas 1.2.5, not this PR. So everything here is good and merged. Thanks for your work.

**Comment by ypraveen** [comment]
@glossner
Great work!

**Pull request merged**
