### PR TITLE
Adding support for NYSE holidays prior to 1971

### PR DESCRIPTION
**Pull request by pldrouin**
Adding support for NYSE holidays prior to 1971. Rules of many holidays differed before 1971. Many ad hoc holidays during that period were added as well. The changes cover holidays between 1/1/1928 and 1/1/1971. Results were verified using http://www.tradingtheodds.com/nyse-full-day-closings/ and S&P 500 daily data (from Macrotrends).

### CODE REVIEW

**Comment by rsheftel** [comment]
This is great thank you. Would it be possible to add some tests so that in the future if changes are made to this we can make sure it does not break the work you have done.

**Comment by pldrouin** [comment]
Ok I will work on that. It would basically consists in making sure that all known NYSE market holidays are present and that no extra full day holidays have been inserted, for the period I have verified (from January 1st 1928 to 2017).

**Comment by rsheftel** [comment]
Maybe a csv file of all the holidays and then can do a full load and compare

**Comment by pldrouin** [comment]
Done. I added a test function and a csv.

**Comment by rsheftel** [comment]
Thanks for the effort!

**Comment by pldrouin** [comment]
Thank you for accepting the request!

**Pull request merged**
