### PR TITLE
Cache holidays

### PR DESCRIPTION
**Pull request by 2torus**
Addresses #108 
Cache holidays computation in order to improve running time of repeated valid_days calls.

### CODE REVIEW

**Review by leonarduschen — APPROVED** [review]
I'm not sure if the computational time bottleneck for `valid_days` at #108  is really `CustomBusinessDay()` and not `pd.date_range()` though. Have you checked @2torus ?

In any case, this looks like an improvement (though perhaps only partially addresses # 108) to me.

**Comment by leonarduschen** [comment]
Awesome. I tried caching the whole `valid_days()` method a few days ago by storing a very long `pd.date_range()` on class initialization and managed to get similar results, but I decided to scrape the idea off because it feels very inelegant!

This seems like a far superior solution, much cleaner and not much extra memory.

**Comment by 2torus** [comment]
@leonarduschen I agree. The user could ask for 40-50 years worth of dates, you don't want to be taking the caching decision for them. Holidays, otoh, is not something you expect to be changing.

**Comment by rsheftel** [comment]
Thanks for this.

**Comment by 2torus** [comment]
@leonarduschen @rsheftel Thank you for allowing me to contribute. I would love to help out in the future. Especially with the quantopian merger.

**Comment by rsheftel** [comment]
@2torus thanks for your work. Maybe a good place to start helping on the merger would be looking at the calendar and code differences and seeing if you can help determine what is the correct calendar days, or help with adding the functionality to trading_calendars to close the gap.

https://github.com/quantopian/trading_calendars/issues/152

https://github.com/quantopian/trading_calendars/issues/151

**Pull request merged**
