### PR TITLE
Fix NYSE test_all_full_day_holidays_since_1928()

### PR DESCRIPTION
**Pull request by lks100**
I eliminated the request argument.  The file now passes all the tests.

### CODE REVIEW

**Comment by rsheftel** [comment]
What tests were failing? I see everything as passing prior to this change.

**Comment by lks100** [comment]
The test 

test_all_full_day_holidays_since_1928() in test_nyse_calendar.py failed for me.  I ran:

python -m nose

in the top level directory.

This is because the routine takes a request argument, but no such argument is passed in when I run the tests this way.  My change just eliminates the argument and figures out the directory containing the test module.

**Comment by rsheftel** [comment]
The test suite requires pytest. Try using pytest and all tests will pass

**Comment by lks100** [comment]
Indeed the tests do pass with pytest.

Feel free to ignore the patch if you don't want compatibility with nose.

**Comment by rsheftel** [comment]
Thanks for the contribution but I am going to focus on pytest for now and I believe it is the recommended test runner.

**Pull request closed without merging**
